### ISSUE TITLE
How to download data

### ISSUE THREAD

**Issue by taoyang1122** [wx-cie/DeepGenGrep#1]
Thanks for the great work! I was trying to get the data used in the paper. I see there are some .txt files in the Data/ folder, but I am not sure how to download it. Could you please let me know how to download the data? Thanks very much!

**Comment by wx-cie** [comment]
You can download the whole project from github use the code `git clone git@github.com:wx-cie/DeepGenGrep.git`

**Comment by taoyang1122** [comment]
Sorry I may not explain the problem clearly. I don't know how to download the data. For example, the bt_neg_PAS.txt has some information like below, how could I get the data. I try to run the codes following the command in README. It doesn't download data automatically.
```
version https://git-lfs.github.com/spec/v1
oid sha256:6e971858c9647a7a10b7cc38dd72bc893dfc36406c17e14ffaaeb4d2917797aa
size 7273364
```

**Comment by wx-cie** [comment]
I am very sorry that the data could not be downloaded. Because the data volume of data has exceeded the maximum value of github, it cannot be downloaded through github. You can get data through Google Drive:[https://drive.google.com/file/d/1P4MgOK7BVf9D1zbysPt3aHaK3IUhbG63/view?usp=sharing](url)

**Comment by taoyang1122** [comment]
Thanks very much for your help!
